### ISSUE TITLE
Issue on page /igpc/library-routines.html

### ISSUE THREAD

**Issue by lyehengfoo** [igcompsci/igcompsci.github.io#2]
SUBSTRING() function - The start position does not accept a variable or calculated value.

Str <-"Happy Days" 
P <- 5
C <- 3
OUTPUT SUBSTRING(Str, LENGTH(Str)-5, C)
OUTPUT SUBSTRING(Str, P, C)
OUTPUT SUBSTRING(Str, 5, C)

Returns:
Hap
Hap
y D

**Comment by hilarryxu** [comment]
issure fixed, refresh page (maybe use Ctrl+F5)

**Comment by lyehengfoo** [comment]
Thank you very much for the fixes. It works perfectly now 👍
